"""최신 모델 변경분 반영

Revision ID: 231cfbbc4d2b
Revises: 3f9f8e8bb0e4
Create Date: 2025-10-22 21:21:08.676881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '231cfbbc4d2b'
down_revision: Union[str, Sequence[str], None] = '3f9f8e8bb0e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_day_key'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('day_key', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('articles_pkey')),
    sa.UniqueConstraint('day_key', 'url', name=op.f('uq_article_day_url'))
    )
    op.create_index(op.f('ix_articles_day_key'), 'articles', ['day_key'], unique=False)
    # ### end Alembic commands ###
