"""auto

Revision ID: 39266f60442b
Revises: e778cbd5d789
Create Date: 2025-11-15 18:04:06.298713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39266f60442b'
down_revision: Union[str, Sequence[str], None] = 'e778cbd5d789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reform_comments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reform_comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reform_comments', 'comment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('reform_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reform_images', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reform_images', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('reform_posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reform_posts', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('reform_posts', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('reform_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_reform_posts_id'), table_name='reform_posts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reform_posts_id'), 'reform_posts', ['id'], unique=False)
    op.alter_column('reform_posts', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reform_posts', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('reform_posts', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('reform_posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reform_images', 'image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('reform_images', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reform_comments', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reform_comments', 'comment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('reform_comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reform_comments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
