"""add mission rp and game tables

Revision ID: 788fda0483f2
Revises: 509385839163
Create Date: 2025-11-22 23:06:43.314886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788fda0483f2'
down_revision: Union[str, Sequence[str], None] = '509385839163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_animals_id'), 'active_animals', ['id'], unique=False)
    op.create_table('daily_mission_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mission_key', sa.String(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('claimed', sa.Boolean(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_mission_state_id'), 'daily_mission_state', ['id'], unique=False)
    op.create_index(op.f('ix_daily_mission_state_mission_key'), 'daily_mission_state', ['mission_key'], unique=False)
    op.create_table('user_rp',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_index(op.f('ix_owned_active_animals_id'), table_name='owned_active_animals')
    op.drop_index(op.f('ix_owned_active_animals_user_id'), table_name='owned_active_animals')
    op.drop_table('owned_active_animals')
    op.drop_index(op.f('ix_owned_animals_user_id'), table_name='owned_animals')
    op.create_foreign_key(None, 'owned_animals', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_owned_objects_user_id'), table_name='owned_objects')
    op.create_foreign_key(None, 'owned_objects', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_placed_objects_user_id'), table_name='placed_objects')
    op.create_foreign_key(None, 'placed_objects', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'placed_objects', type_='foreignkey')
    op.create_index(op.f('ix_placed_objects_user_id'), 'placed_objects', ['user_id'], unique=False)
    op.drop_constraint(None, 'owned_objects', type_='foreignkey')
    op.create_index(op.f('ix_owned_objects_user_id'), 'owned_objects', ['user_id'], unique=False)
    op.drop_constraint(None, 'owned_animals', type_='foreignkey')
    op.create_index(op.f('ix_owned_animals_user_id'), 'owned_animals', ['user_id'], unique=False)
    op.create_table('owned_active_animals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('animal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('owned_active_animals_pkey'))
    )
    op.create_index(op.f('ix_owned_active_animals_user_id'), 'owned_active_animals', ['user_id'], unique=False)
    op.create_index(op.f('ix_owned_active_animals_id'), 'owned_active_animals', ['id'], unique=False)
    op.drop_table('user_rp')
    op.drop_index(op.f('ix_daily_mission_state_mission_key'), table_name='daily_mission_state')
    op.drop_index(op.f('ix_daily_mission_state_id'), table_name='daily_mission_state')
    op.drop_table('daily_mission_state')
    op.drop_index(op.f('ix_active_animals_id'), table_name='active_animals')
    op.drop_table('active_animals')
    # ### end Alembic commands ###
