"""Add kakao_id to user table

Revision ID: aa6611aae647
Revises: f2df8749f681
Create Date: 2025-10-16 14:58:18.281597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa6611aae647'
down_revision: Union[str, Sequence[str], None] = 'f2df8749f681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'garment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('kakao_id', sa.BigInteger(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_kakao_id'), 'users', ['kakao_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_kakao_id'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'kakao_id')
    op.alter_column('events', 'garment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
