"""update event model to garment_id

Revision ID: f2df8749f681
Revises: 07eb61be81bb
Create Date: 2025-10-14 19:17:16.885722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2df8749f681'
down_revision: Union[str, Sequence[str], None] = '07eb61be81bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('events', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('events', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('events_garment_id_fkey'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('events_user_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'events', 'clothes', ['garment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_user_id_fkey'), 'events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('events_garment_id_fkey'), 'events', 'clothes', ['garment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('events', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('events', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
